name: entropic_barrier
channels:
- defaults
dependencies:
- h5py
- matplotlib
- numba=0.39
- numpy
- pandas
- pandoc
- python=3.6
- scipy
- sympy=1.2
- tqdm
- cython
- ipython
- jupyter
- pip:
  - sacred=0.7.4

